version: '3.4'
services:
  multy-back:
    image:  multyio/multy-back:stage
    # build: .
    #command: ["make", "all"]
    env_file: .env
    volumes:
        - "${BACKEND_LOGS}:/go/src/github.com/Appscrunch/Multy-back/cmd/logs"
        - "${BACKEND_CONF}:/go/src/github.com/Appscrunch/Multy-back/cmd/multy.config"
        #- "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-back/cmd/rpc.cert"
    ports:
      - "6778:6778"
      - "6780:6780"
    depends_on:
      - btc-node-service-mainnet
      - btc-node-service-testnet
      - nsq
      - nsqlookup
      - nsqadmin
      - mongodb


  btc-node-service-mainnet:
    image: multyio/multy-btc-node-service
    hostname: btc-node-service-mainnet
    network_mode: "host"
    volumes:
      - "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-BTC-node-service/cmd/rpc.cert"
      - "${BTC_NODE_SERVICE_MAINNET}:/go/src/github.com/Appscrunch/Multy-BTC-node-service/cmd/client.config"
    ports:
      # - "7770:7770"
      - "7000:7000"
    depends_on:
      - nsq


  btc-node-service-testnet:
    image: multyio/multy-btc-node-service
    network_mode: "host"
    volumes:
      - "${BTC_NODE_SERVICE_TESTNET}:/go/src/github.com/Appscrunch/Multy-BTC-node-service/cmd/client.config"
      - "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-BTC-node-service/cmd/rpc.cert"
    ports:
      # - "6660:6660"
      - "6000:6000"
    depends_on:
      - nsq



  mongodb:
    container_name: "mongo_db"
    image: mongo:3.6.2
    env_file: .env
    command: mongod --smallfiles
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_LOG_DIR}:/data/logs
    ports:
      - 27017:27017

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "6160:4160"
      - "6161:4161"
    command: nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "6150:4150"
      - "6151:4151"
    links:
      - nsqlookup:nsqlookup
    env_file: .env
    environment:
      - NSQD_DATA_DIR=/data/nsqd
    volumes:
      - ${NSQD_DATA_DIR}:/data/nsqd
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 -data-path=/data

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "6171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookup:4161
