version: '3.4'
services:
  multy-back-test:
    image:  multyio/multy-back-prod:latest
    # build: .
    #command: ["make", "all"]
    env_file: .env
    volumes:
        - "${BACKEND_LOGS}:/go/src/github.com/Appscrunch/Multy-back/cmd/logs"
        - "${BACKEND_CONF}:/go/src/github.com/Appscrunch/Multy-back/cmd/multy.config"
        - "${BTCD_CERT}:/go/src/github.com/Appscrunch/Multy-back/cmd/rpc.cert"
    ports:
      - "5578:7778"
      - "5580:7780"
    depends_on:
      - nsq-test
      - nsqlookup-test
      - nsqadmin-test
      - mongodb-test
      # - btcd-testnet

  mongodb-test:
    container_name: "mongo_db_test"
    image: mongo:3.6.2
    env_file: .env
    command: mongod --smallfiles
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      - ${MONGO_LOG_DIR}:/data/logs
    ports:
      - 27016:27017

  nsqlookup-test:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "5160:4160"
      - "5161:4161"
    command: nsqlookupd

  nsq-test:
    image: nsqio/nsq
    hostname: nsq-test
    ports:
      - "5150:4150"
      - "5151:4151"
    links:
      - nsqlookup-test:nsqlookup
    env_file: .env
    environment:
      - NSQD_DATA_DIR=/data/nsqd
    volumes:
      - ${NSQD_DATA_DIR}:/data/nsqd
    command: nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 -data-path=/data

  nsqadmin-test:
    image: nsqio/nsq
    hostname: nsqadmin-test
    links:
      - nsqlookup-test:nsqlookup
    ports:
      - "5171:4171"
    command: nsqadmin --lookupd-http-address=nsqlookup:4161
